language: python
python:
  - 2.7
env:
  - DJANGO=django==1.8c1
install:
  - travis_retry pip install $DJANGO
  - pip install genshi
  - pip install flake8
  - pip install -e .
before_script:
  - flake8 django_genshi_template
script:
  tests/runtests.py